### ISSUE TITLE
Text for Verify External Destinations is rough

### ISSUE THREAD

**Issue by smjones** [ietf-wg-dmarc/draft-ietf-dmarc-failure-reporting#6]
The existing text for Section 5, Verifying External Destinations, is rather terse. It barely describes the functionality by reference to aggregate-reporting, and gives no mention to the reason for doing it. I'll propose a diff that brings it inline with aggregate-reporting, includes context, and cites the verification procedure with a missing modification.

**Comment by smjones** [comment]
Current text:
  
    If the target domain of a mailto address of a ruf= tag is not the
    same as the DMARC record domain where the tag was found, the report
    generator MUST verify that the target domain acknowledges sending
    those reports; the procedure is described in Section 3 of
    [I-D.ietf-dmarc-aggregate-reporting].`

Proposed text:
  
    It is possible to specify destinations for failure reports that are
    outside of the domain requesting the reports.  These destinations are
    commonly referred to as "external destinations" and may represent a
    different domain controlled by the same organization, a contracted
    report processing service, or some other arrangement.
 
    Without this check, a bad actor could publish a DMARC policy record
    that requests that failure reports be sent to an external
    destination, then deliberately send messages that will generate
    failure reports as a form of abuse.  Or, a domain owner could
    incorrectly publish a DMARC policy with an external destination for
    failure reports, forcing the external destination to deal with
    unwanted messages and potential privacy issues.
 
    Therefore a Mail Receiver who generates failure reports MUST use the
    Verifying External Destinations procedure described in Section 3 of
    [I-D.ietf-dmarc-aggregate-reporting], substituting the "ruf=" tag
    where the "rua=" tag appears in that procedure.`

**Comment by alevesely** [comment]
I added that text to the `.md` file and pushed it.  I only modified the last paragraph slightly like so:

```mmark
Therefore, in case of external destinations, a Mail Receiver who 
generates failure reports **MUST** use the Verifying External Destinations 
procedure described in [@!I-D.ietf-dmarc-aggregate-reporting, section 3], 
substituting the "ruf=" tag where the "rua=" tag appears in that procedure.`
```

If that's ok I'll post version -12 to the IETF.

**Comment by smjones** [comment]
Thought I’d see if anybody else had an opinion before merging. I anticipate some additional tweaks after this one. Sent from my iPhoneOn Nov 21, 2024, at 9:30 PM, Alessandro Vesely ***@***.***> wrote:﻿
I added that text to the .md file and pushed it.  I only modified the last paragraph slightly like so:
Therefore, in case of external destinations, a Mail Receiver who 
generates failure reports **MUST** use the Verifying External Destinations 
procedure described in [@!I-D.ietf-dmarc-aggregate-reporting, section 3], 
substituting the "ruf=" tag where the "rua=" tag appears in that procedure.`

If that's ok I'll post version -12 to the IETF.
